### ISSUE TITLE
JpaUtils.countCriteria fails when the original criteria has fetches

### ISSUE THREAD

**Issue by v-mihaylov** [chelu/jdal#3]
The exception I get is: 
org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list.

When I comment the copy Fetches part in copyJoins, everything works as expected.

Thanks for writing and sharing all this!

**Comment by chelu** [comment]
Hi Mihaylov, 

Thanks for reporting this.  
JDAL issue tracker is at http://jira.jdal.org.
Please,  Could you fire the issue there?.

Thanks, 

- Jose Luis

**Comment by chelu** [comment]
The issue is now fixed:  http://jira.jdal.org/browse/JDAL-15
